#!/usr/bin/bash

if [ "$1" = "2080" ]; then
echo "Entering GPU computing node with 2080Ti GPUs..."
srun -A lr_ninjaone -p es1 -q condo_ninjaone_es1 -t 6:0:0 --gres=gpu:4 -n 8  -N 1 -C es1_2080ti  --pty bash
elif [ "$1" = "v100" ]; then
echo "Entering GPU computing node with Tesla V100 GPUs..."
srun -A lr_ninjaone -p es1 -q condo_ninjaone_es1 -t 6:0:0 --gres=gpu:2 -n 8  -N 1 -C es1_v100  --pty bash
else
echo "Entering NinjaOne CPU computing node..."
srun -A lr_ninjaone -p csd_lr6_192 -q condo_ninjaone -t 6:0:0 --pty bash
fi
